name: Fast API

on:
  workflow_dispatch:

jobs:
  FastAPI-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository files
        uses: actions/checkout@v4

      - name: Verify checked-out files
        run: ls -al
