name: Fast API With Multiple Job
env:
  ARTIFACT_FILE_NAME: "fastapi_artifact.zip"

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository files
        uses: actions/checkout@v4

      - name: Verify checked-out files
        run: ls -al

      - name: Prepare the environment for build
        run: |
             echo "************START APT UPDATE*******"
             sudo apt update
             echo "************END APT UPDATE*******"
             echo "************START INSTALLING PYTHON3 AND PIP*******"
             sudo apt install -y python3 python3-pip python3-venv
             echo "************END INSTALLING PYTHON3 AND PIP*******"
             echo "************START VERSION CHECK OF PYTHON3 AND PIP*******"
             python3 --version
             python3 -m pip --version
             echo "************END VERSION CHECK OF PYTHON3 AND PIP*******"
             echo "************START ENVIRONMENT CREATION AND ACTIVATION*******"
             python3 -m venv env1
             source env1/bin/activate
             echo "************END ENVIRONMENT CREATION AND ACTIVATION*******"
             echo "************START VERSION CHECK OF PYTHON AND PIP ON ENVIRONMENT*******"
             python --version
             pip --version
             echo "************END VERSION CHECK OF PYTHON AND PIP ON ENVIRONMENT*******"

      - name: Install the dependancies
        run: |
             echo "************START INSTALING PACKAGES*******"
             pip3 install -r requirements-build.txt
             echo "************END INSTALING PACKAGES*******"
             
      - name: Build the app
        run: ruff checkout .
  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository files
        uses: actions/checkout@v4

      - name: Verify checked-out files
        run: ls -al

      - name: Prepare the environment for test
        run: |
             echo "************START APT UPDATE*******"
             sudo apt update
             echo "************END APT UPDATE*******"
             echo "************START INSTALLING PYTHON3 AND PIP*******"
             sudo apt install -y python3 python3-pip python3-venv
             echo "************END INSTALLING PYTHON3 AND PIP*******"
             echo "************START VERSION CHECK OF PYTHON3 AND PIP*******"
             python3 --version
             python3 -m pip --version
             echo "************END VERSION CHECK OF PYTHON3 AND PIP*******"
             echo "************START ENVIRONMENT CREATION AND ACTIVATION*******"
             python3 -m venv env1
             source env1/bin/activate
             echo "************END ENVIRONMENT CREATION AND ACTIVATION*******"
             echo "************START VERSION CHECK OF PYTHON AND PIP ON ENVIRONMENT*******"
             python --version
             pip --version
             echo "************END VERSION CHECK OF PYTHON AND PIP ON ENVIRONMENT*******"

      - name: Install the dependancies
        run: |
             echo "************START INSTALING PACKAGES*******"
             pip install -r requirements-test.txt
             echo "************END INSTALING PACKAGES*******"

      - name: Do the test
        run: pytest

  Artifact:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository files
        uses: actions/checkout@v4

      - name: Verify checked-out files
        run: ls -al

      - name: "Create ${{env.ARTIFACT_FILE_NAME}}"
        run: zip -r "${{ env.ARTIFACT_FILE_NAME }}" . -x "env1/*" "*/env1/*" ".git/*" ".github/*" "*.DS_Store"

      - name: Create artiface
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.ARTIFACT_FILE_NAME}}
          path: ${{env.ARTIFACT_FILE_NAME}}
          if-no-files-found: error
          retention-days: 7  
