name: Fast API
env:
  ARTIFACT_FILE_NAME: "fastapi_artifact.zip"

on:
  workflow_dispatch:

jobs:
  FastAPI-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository files
        uses: actions/checkout@v4

      - name: Verify checked-out files
        run: ls -al

      - name: Update api
        run: sudo apt update
        
      - name: Install Python
        run: sudo apt install -y python3 python3-pip python3-venv

      - name: Verify the Python Version
        run: python3 --version

      - name: Verify pip version
        run: python3 -m pip --version

      - name: Create environment
        run: python3 -m venv env1

      - name: Activate the environment
        run: source env1/bin/activate

      - name: Check the python and pip versions
        run: |
            python --version
            pip --version

      - name: Install the dependancies
        run: pip install fastapi uvicorn sqlalchemy pytest httpx ruff

      - name: Check the lint
        run: ruff check .

      - name: Do the python test
        run: pytest

      - name: Exit from the environment
        run: deactivate

      - name: List all files in the server
        run: ls -al
        
      - name: Create artiface
        uses: actions/upload-artifact@v4
        with:
          name: Create Artifact
          path: ${{env.ARTIFACT_FILE_NAME}}
          if-no-files-found: error
          retention-days: 7
          
