name: Practice

on:
  push:
    branches:
    - main

jobs:
  First-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: "Lab 1 : First Workflow"
        run: echo 'Hello DevOps'

  Linux-Runner:
    needs: First-Workflow
    runs-on: ubuntu-latest

    steps:
      - name: "Lab 2 : Linux Runner"
        run: |
            echo "  Present Working Directory : " pwd
            echo "  Who am i : " whoami
            echo "  Date : " date
            echo "  User : " user -a

  Repository-Inspection:
    needs: Linux-Runner
    runs-on: ubuntu-latest

    steps:
      - name: "Lab 3 : Repository Inspection"
        run: |
            ls
            ls -a
            find

  Environment-Variables:
    needs: Repository-Inspection
    runs-on: ubuntu-latest

    steps:
      - name: "Lab 4 : Environment Variables"
        run: |
            echo "GITHUB_WORKFLOW : " ${{github.workflow}}
            echo "GITHUB_REPOSITORY : " ${{github.repository}}
            echo "GITHUB_REF : " ${{github.ref}}
            echo "GITHUB_SHA : " ${{github.sha}}
            echo "RUNNER_OS : " ${{runner.os}}
