name: Practice

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Lab 1 : First Workflow"
        run: echo 'Hello DevOps'

      - name: "Lab 2 : Linux Runner"
        run: |
            echo "  Present Working Directory : " pwd
            echo "  Who am i : " whoami
            echo "  Date : " date
            echo "  User : " user -a

      - name: "Lab 3 : Repository Inspection"
        run: |
            ls
            ls -a
            find
