name: Secrets Lab Challenges
env:
  WORKFLOW_VAR: "Workflow Level Variable Value"
  STEP_PRECEDENCE_TEST_VAR: "Workflow"
  JOB_PRECEDENCE_TEST_VAR: "Workflow"

on:
  push:
    branches:
    - main

jobs:
  Lab1-Variable-Scope:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job Level Variable Value"
      JOB_PRECEDENCE_TEST_VAR: "Job"
      

    steps:
      - name: Variable Scope
        run: |
           echo " Variable WORKFLOW_VAR = " ${{env.WORKFLOW_VAR}}
           echo " Variable JOB_VAR = " ${{env.JOB_VAR}}
           echo " Variable STEP_VAR = " ${{env.STEP_VAR}}
           echo " Variable JOB_PRECEDENCE_TEST_VAR = " ${{env.JOB_PRECEDENCE_TEST_VAR}}
           echo " Variable STEP_PRECEDENCE_TEST_VAR = " ${{env.STEP_PRECEDENCE_TEST_VAR}}
        env:
          STEP_VAR: "Step Level Variable Value"
          STEP_PRECEDENCE_TEST_VAR: "Step"
          
