name: Secrets Lab Challenges
env:
  WORKFLOW_VAR: "Workflow Level Variable Value"
  STEP_PRECEDENCE_TEST_VAR: "Workflow"
  JOB_PRECEDENCE_TEST_VAR: "Workflow"
  COURSE: "Linux"

on:
  push:
    branches:
    - main

jobs:
  Lab1-Variable-Scope:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job Level Variable Value"
      JOB_PRECEDENCE_TEST_VAR: "Job"
      

    steps:
      - name: Variable Scope
        run: |
           echo " Variable WORKFLOW_VAR = " ${{env.WORKFLOW_VAR}}
           echo " Variable JOB_VAR = " ${{env.JOB_VAR}}
           echo " Variable STEP_VAR = " ${{env.STEP_VAR}}
           echo " Variable JOB_PRECEDENCE_TEST_VAR = " ${{env.JOB_PRECEDENCE_TEST_VAR}}
           echo " Variable STEP_PRECEDENCE_TEST_VAR = " ${{env.STEP_PRECEDENCE_TEST_VAR}}
        env:
          STEP_VAR: "Step Level Variable Value"
          STEP_PRECEDENCE_TEST_VAR: "Step"

  Lab2-Repository-Variable-VS-Workflow-Variable:
    needs: Lab1-Variable-Scope
    runs-on: ubuntu-latest
    
    steps:
      - name: Repository Variable VS Workflow Variable
        run: |
           echo " Repository Variable COURSE = " ${{vars.COURSE}}
           echo " Workflow Variable COURSE = " ${{env.COURSE}}

  Lab3-Missing-Repository-Variable:
    needs: Lab2-Repository-Variable-VS-Workflow-Variable
    runs-on: ubuntu-latest
    
    steps:
      - name: Missing Repository Variable
        run: |
           echo " Repository Variable COURSE = " ${{vars.COURSE}}
           echo " Workflow Variable COURSE = " ${{env.COURSE}}
           echo " Missing Repository Variable COURSE1 = " ${{vars.COURSE1}}
