name: This is the new deployment line

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch repository code
      uses: actions/checkout@v7
      
    - name: This is the job to display the directory structure
      run: ls -al

    - name: This is the job to display date
      run: date
