name: Website CI
env:
  APP_NAME: ${{vars.APPLICATION_NAME}} 
  ENVIRONMENT: development
  COMPANY: CloudNova
 
on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Application Name ${{env.APP_NAME}}
      run: echo "Verify the following details" $APP_NAME $ENVIRONMENT $COMPANY
      env:
        APP_NAME: Test App
        ENVIRONMENT: Test Environment
 
    - name: Display ls for ${{env.COMPANY}}.${{env.ENVIRONMENT}}.${{env.APP_NAME}}
      run: ls 
      
  verify:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
    - name: GitHub Details
      run: |
         echo "Actor = " ${{github.actor}}
         echo "repository = " ${{github.repository}}
         echo "Ref = " ${{github.ref}}
         echo "Sha = " ${{github.sha}}
         
    - name: Finished
      run: echo Finished
